# Generated by Django 4.1.4 on 2022-12-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='app.match'),
        ),
    ]
